name: Generate GitHub Stats SVG

on:
  schedule:
    - cron: "0 */24 * * *"  # Runs every 24 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate transparent GitHub stats
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate stats
        uses: anuraghazra/github-readme-stats@v2
        with:
          username: omardiop
          show_icons: true
          hide_border: true
          bg_color: 00000000
          title_color: 58a6ff
          text_color: c9d1d9
          icon_color: 79c0ff
          include_all_commits: true
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Update transparent stats"
